default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= Rails.application.credentials.pg.host %>
  username: <%= Rails.application.credentials.pg.username %>
  password: <%= Rails.application.credentials.pg.password %>
  port: <%= Rails.application.credentials.pg.port %>

development:
  <<: *default
  database: blog_development

test:
  <<: *default
  database: blog_test

production:
  <<: *default
  database: blog_production
  username: blog
  password: <%= ENV["BLOG_DATABASE_PASSWORD"] %>
